version: '3.0'
services:
  web:
    image: alexcheng/magento2:2.2
    volumes: 
      - web-data:/var/www/html
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  db-data:
  web-data: 